version: '3.5'
services:
  web_dev:
    build: .
    ports:
     - "4000:4000"
    volumes:
     - .:/usr/src/app
    environment:
     - ENV=development
     - PORT=4000
     - DB=mongodb+srv://dbuser:dbuser@cluster.mongodb.net/todo_db?retryWrites=true&w=majority
     - SECRET='to-do-app-secret'
networks: 
  default:
    name: web_dev